name: Loan_prediction
channels:
  - default
dependencies:
- python=3.11.8
- pip<=23.2.1
- pip:
  - matplotlib==3.7.2
  - mlflow==2.11.3
  - numpy==1.24.3
  - pandas==2.0.3
  - scikit_learn==1.3.0
  - pyyaml==6.0.1
  - scipy==1.11.2
  - cloudpickle==2.2.1